apiVersion: apps/v1
kind: Deployment
metadata:
  name: otp-generation
  #namespace: interns-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: otp-generation
        image: divakar22/otpprojectapi
---
apiVersion: v1
kind: Service
metadata:
  name: otp-service
  #namespace: interns-dev
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002